language: generic 

sudo: required
services:
    - docker

before_install:
    - dokcer build-t dduvedi/docker-frontend-travis -f Docfile.dev .

script:
    - docker run dduvedi/docker-frontend-travis npm run test -- --coverage